# Composeのバージョンを指定
version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    container_name: gourmet-app-front
    volumes:
      - ./app:/app
    ports:
      - "5173:5173"

